name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Stop old builds
        if: github.ref != 'refs/heads/master'
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        java-version: [ 8, 11 ]
        jacoco: [true, false]
        exclude:
         - os: macos-latest
           jacoco: true
         - os: ubuntu-latest
           jacoco: true
           java-version: 11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Build & Test
        run: ./mvnw -B verify
      - name: Generate JaCoCo Badge
        if: ${{ matrix.jacoco }}
        id: jacoco
        with:
          generate-branches-badge: true
